#!/bin/bash
# dialog box will display a menu 

# global var / default val
MENUBOX=${MENUBOX=dialog}

#func declarations - start 

# func to display a simple menu 
funcDisplayDialogMenu () {
	$MENUBOX --title " [ M A I N  M E N U ] " --menu " Use UP/DOWN Arrows to Move and Selecto or the Number of Your Choise and Enter" 15 45 4 1 "Display Hello World " 2 "Display Goodbye World" 3 "Display Nothing" X "Exit" 2>choice.txt
}
echo $?

# scr - start 
funcDisplayDialogMenu 

case "`cat choice.txt`" in
	1) echo " Hello world ";;
	2) echo " Goodbye World ";;
	3) echo " Nothing ";;
	X) echo " Exit ";;
esac

echo $?
# scr - stop

